name: icibot_rs_data_plugin
description: Plugin for RSData implementation
version: 1.0.2
# repository: https://github.com/ascobani/icibot_rs_data_plugin


environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  dio: ^5.0.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1
  isar_generator: ^3.0.5
  build_runner: ^2.3.3
  test: ^1.23.1


