name: icibot_rs_data_plugin
version: 1.0.17
publish_to: https://onepub.dev/api/xxapsdavuh/
description: Plugin for RSData implementation
environment: 
  sdk: '>=2.19.0 <4.0.0'
dependencies: 
  dio: ^5.1.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.14
dev_dependencies: 
  flutter_lints: ^2.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.3.3
  flutter_test: 
    sdk: flutter
