name: icibot_rs_data_plugin
description: Plugin for RSData implementation
version: 1.0.13
# repository: https://github.com/ascobani/icibot_rs_data_plugin

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  dio: ^5.1.1
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  isar_generator: ^3.1.0
  build_runner: ^2.3.3
  test: ^1.24.1
